# Generated by Django 4.1.1 on 2022-09-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likers_count",
            field=models.IntegerField(default=0),
        ),
    ]
